### PR TITLE
Created Rotten Flesh Block and Made Rotten flesh smelt into leather, for real this time

### PR DESCRIPTION
**Pull request by fewffwa**

### CODE REVIEW

**Review by collectioncard — CHANGES_REQUESTED** [review]
Its almost there but needs a few changes. I left comments on some of the issues. Also, you should add an entry for pirate speak since we are supporting that. @Trademark124 can probably help with that.

**Review by collectioncard — APPROVED** [review]
I changed a few indents and cleaned up a few things. The rest of your changes look good. I just want @Copetan to look over it real quick and see if there is anything else.

**Review by Copetan — APPROVED** [review]
I'm just gonna pull the damn pr already

**Comment by collectioncard** [comment]
You're the one who set it to require two reviews, lol

**Pull request merged**
